<a href="https://colab.research.google.com/github/eovallemagallanes/Digital-Image-Processing/blob/main/lecture0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Image processing in Python

## Python’s Mathematical Libraries

* [NumPy](https://numpy.org/) (Numerical Python): 

---
NumPy arrays are the equivalent to the basic array data structure in MATLAB. With NumPy arrays, you can do things like inner and outer products, transposition, and element-wise operations. NumPy also contains a number of useful methods for reading text and binary data files, fitting polynomial functions, many mathematical functions (sine, cosine, square root, and so on), and generating random numbers.


* [SciPy](https://docs.scipy.org/doc/scipy/reference/) (Scientific Python):

---
The SciPy package (as distinct from the SciPy stack) is a library that provides a huge number of useful functions for scientific applications. If you need to do work that requires optimization, linear algebra or sparse linear algebra, discrete Fourier transforms, signal processing, physical constants, image processing, or numerical integration, then SciPy is the library for you! Since SciPy implements so many different features, it’s almost like having access to a bunch of the MATLAB toolboxes in one package.


* [Matplotlib](https://matplotlib.org/) (MATLAB-like Plotting Library):

---
Matplotlib is a library to produce high-quality and interactive two-dimensional plots. Matplotlib is designed to provide a plotting interface that is similar to the plot() function in MATLAB, so people switching from MATLAB should find it somewhat familiar. Although the core functions in Matplotlib are for 2-D data plots, there are extensions available that allow plotting in three dimensions with the mplot3d package, plotting geographic data with cartopy, and many more listed in the Matplotlib documentation.

* [Scikit-image](https://scikit-image.org/):

---
scikit-image is a Python package dedicated to image processing, and using natively NumPy arrays as image objects

## Syntax Differences Between MATLAB® and Python

* Comments Start With # in Python

---
```python
# This is a comment
```

* Indentation 

---
```matlab
% Matlab code
num = 10;

if num == 10
disp("num is equal to 10")
else
disp("num is not equal to 10")
end

disp("I am now outside the if block")

```



In [1]:
num = 10
a = 0

if num == 10:
    print("num is equal to 10")
    a = 20
    print(a)
else:
    print("num is not equal to 10")
    a = 30
    print(a)

a = 40
print(a)
print("I am now outside the if block")

num is equal to 10
20
40
I am now outside the if block


* Conditional statements

---
```matlab
% Matlab code
num = 10;
if num == 10
    disp("num is equal to 10")
elseif num == 20
    disp("num is equal to 20")
else
    disp("num is neither 10 nor 20")
end
```

In [2]:
num = 10
if num == 10:
    print("num is equal to 10")
elif num == 20:
    print("num is equal to 20")
else:
    print("num is neither 10 nor 20")

num is equal to 10


* Calling Functions and Indexing Sequences

---
```matlab
% Matlab code
arr = [10, 20, 30];
arr(1)

ans =

    10

sum(arr)

ans =

    60

```

In [4]:
arr = [10, 20, 30]
print(arr[0])


sum(arr)

10


60

* Indexing

---
```matlab
% Matlab code
arr = [10, 20, 30];
arr(1)

ans =

    10

arr(0)
Array indices must be positive integers or logical values.


arr(end)

ans =

    30
```



In [5]:
arr = [10, 20, 30]
print(arr[0])
print(arr[1])
print(arr[-1])


a_string = "a string"
print(a_string[0])
print(a_string[1])

10
20
30
a
 


* Exponentiation

---
```matlab
% Matlab code
10^2

ans =

    100
```


In [6]:
10 ** 2

100

* The Length of a Sequence

---
```matlab
% Matlab code
length([10, 20, 30])

ans =

    3

length("a string")

ans =

    8
```

In [7]:
print(len([10, 20, 30]))
print(len("a string"))

3
8


* Function Definitions

---
```matlab
% Matlab code
function [total] = addition(num_1,num_2)
total = num_1 + num_2;
end

var_1 = 20;
var_2 = 10;
sum_of_vars = addition(var_1,var_2)

sum_of_vars =

    30
```

In [8]:
def addition(num_1, num_2):
    total = num_1 + num_2
    return total

var_1 = 20
var_2 = 10
sum_of_vars = addition(var_1, var_2)
print(sum_of_vars)

30


* Anonymous Functions: 

---
MATLAB uses the the at-symbol (@) to indicate that what follows is the definition of an anonymous function. Anonymous functions are functions that are not defined in a program file and do not use the function keyword.

---
```matlab
% Matlab code
f = @(X) 100*(X(2)-X(1).^2).^2+(1-X(1)).^2;

X0=[2 2]'
f(X0) = 
    401
```

In [9]:
f = lambda X: 100*(X[1]-X[0]**2)**2+(1-X[0])**2

X0 = [2, 2]
f(X0)

401

In [10]:
type(X0)

list

## List operations (problems)

In [11]:
arr_1 = [1, 2, 3]
arr_2 = [4, 5, 6]

print(arr_1 * arr_2)

TypeError: ignored

In [12]:
arr_1**2

TypeError: ignored

In [14]:
arr_1*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

## Basic Array Operations

* Element-Wise

---
```matlab
% Matlab code
arr_1 = [1,2,3];
arr_2 = [4,5,6];
arr_1 * arr_2

Error using  *
Incorrect dimensions for matrix multiplication. Check that the number of
columns in the first matrix matches the number of rows in the second
matrix. To perform elementwise multiplication, use '.*'.

arr_1 .* arr_2

ans =

     4    10    18


arr_1 * arr_2'

ans =

    32
```

In [15]:
import numpy as np

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

print(arr_1 * arr_2)
print(arr_1 @ arr_2)
print(np.dot(arr_1, arr_2))

[ 4 10 18]
32
32


In [19]:
type(arr_1)

numpy.ndarray

## Creating Arrays 

In MATLAB, you can use a colon to create an array specification range. In general, you can use up to 2 colons in a specification. The syntax is as follows:

---
start : stop

start : step : stop

---
```matlab
arr_1 = 1:6

arr_1 =

     1     2     3     4     5     6

size(arr_1)

ans =

     1     6
```

There are three ways to use arange():

---
```python
import numpy as np
np.arange(stop)
np.arange(start, stop)
np.arange(start, stop, step)
```


In [20]:
import numpy as np

# type 1
arr_1 = np.arange(7)
print(arr_1)
print(arr_1.shape)

# type 2
arr_2 = np.arange(1, 7, 2)
print(arr_2)

# type 3
arr_3 = np.arange(2, 7, 2)
print(arr_3)

[0 1 2 3 4 5 6]
(7,)
[1 3 5]
[2 4 6]


In [21]:
print(arr_1)
print(arr_1.shape)
arr_1_T = arr_1.T
print(arr_1_T)
print(arr_1_T.shape)

[0 1 2 3 4 5 6]
(7,)
[0 1 2 3 4 5 6]
(7,)


In [22]:
res = arr_1 * arr_1
print(res)
print(res.shape)

[ 0  1  4  9 16 25 36]
(7,)


In [23]:
arr_1 @ arr_1_T

91

In [24]:
arr_4 = np.expand_dims(arr_1, -1)
print(arr_4.shape)

arr_4_T = arr_4.T
print(arr_4_T.shape)

(7, 1)
(1, 7)


In [25]:
arr_4 @ arr_4_T

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  2,  4,  6,  8, 10, 12],
       [ 0,  3,  6,  9, 12, 15, 18],
       [ 0,  4,  8, 12, 16, 20, 24],
       [ 0,  5, 10, 15, 20, 25, 30],
       [ 0,  6, 12, 18, 24, 30, 36]])

In [26]:
arr_4.T @ arr_4

array([[91]])

In [27]:
arr_5 = arr_4 * arr_4
print(arr_5)
print(arr_5.shape)

[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]
 [25]
 [36]]
(7, 1)


In [47]:
a = np.arange(15).reshape(3, 5)
n,m = a.shape

In [48]:
b = a.reshape(n*m,1)
b.shape

(15, 1)

In [49]:
c = a.ravel()
c.shape

(15,)